elm.json
src/Morphir/SDK/Key.elm

Added Key module. #103

---

src/Morphir/Elm/Frontend.elm
src/Morphir/IR/Value.elm

Added missing docs

---

src/Morphir/Elm/Frontend/Resolve.elm
tests-integration/reference-model/src/Morphir/Reference/Model/Values.elm
tests/Morphir/Elm/Frontend/ResolveTests.elm

Add support for resolving record constructors. #129

---

package.json

Allow gen file to be included in the package

---

src/Morphir/Elm/Frontend.elm
tests/Morphir/Elm/FrontendTests.elm

Fix associativity

---

src/Morphir/Elm/Frontend.elm
tests/Morphir/Elm/FrontendTests.elm

Resolve constructor patterns

---

cli/cli.js
cli/morphir-elm-gen.js
cli/morphir-elm-make.js
package.json

Removed stdout/stdin defaults and replaced with 'morphir-ir.json'.

---

cli/src/Morphir/Elm/DaprCLI.elm
src/Morphir/Elm/Frontend.elm
src/Morphir/Elm/Frontend/Resolve.elm
src/Morphir/IR/Module.elm
src/Morphir/IR/Module/Codec.elm
src/Morphir/IR/Package.elm
src/Morphir/IR/Package/Codec.elm
src/Morphir/IR/SDK.elm
src/Morphir/IR/SDK/Basics.elm
src/Morphir/IR/SDK/Char.elm
src/Morphir/IR/SDK/Dict.elm
src/Morphir/IR/SDK/List.elm
src/Morphir/IR/SDK/Maybe.elm
src/Morphir/IR/SDK/Regex.elm
src/Morphir/IR/SDK/Result.elm
src/Morphir/IR/SDK/String.elm
src/Morphir/IR/SDK/Tuple.elm
src/Morphir/Scala/Backend.elm
tests/Morphir/Elm/Frontend/ResolveTests.elm
tests/Morphir/Elm/FrontendTests.elm

Different annotation type between types and values

---

elm.json
src/Morphir/SDK/String.elm

Initial version of string module. #179

---

src/Morphir/IR/SDK/Dict.elm
src/Morphir/IR/SDK/Set.elm
tests-integration/reference-model/morphir.json
tests-integration/reference-model/src/Morphir/Reference/Model/Issues/Issue210.elm

Reproduce and fix missing type signatures for Set. #210

---

cli/src/Morphir/Web/DevelopMain.elm

Invoke visualization components from developer server. #218

---

src/Morphir/Graph/GraphViz/AST.elm
src/Morphir/Graph/GraphViz/PrettyPrint.elm
src/Morphir/Graph/GraphVizBackend.elm
tests-integration/reference-model/morphir.json

GraphViz backend skeleton. #253

---

src/Morphir/Graph/GraphViz/AST.elm
src/Morphir/Graph/GraphViz/PrettyPrint.elm
src/Morphir/Graph/GraphVizBackend.elm

Improvements on GraphViz backend. #253

---

src/Morphir/Visual/ViewIfThenElse.elm
src/Morphir/Visual/ViewValue.elm

Integrate GraphViz backend. #253

---

src/Morphir/SpringBoot/Backend.elm

Method to redirect home page to swagger UI Page

---

cli/.gitignore
cli/web/index.html
cli/web/main.js
src/Morphir/Graph/GraphViz/PrettyPrint.elm
src/Morphir/Graph/GraphVizBackend.elm
src/Morphir/Visual/ViewIfThenElse.elm
src/Morphir/Visual/ViewValue.elm
tests-integration/reference-model/src/Morphir/Reference/Model/Values.elm
tests-integration/reference-model/tests/Morphir/Reference/Model/BooksAndRecordsTests.elm

Graph Visualization for If else expression.

---

docs/springboot/README.md

Documentation regarding Spring Boot generate

---

src/Morphir/SDK/LocalDate.elm

Elm documentation

---

cli/morphir-elm-develop.js
cli/src/Morphir/Elm/CLI.elm
cli/src/Morphir/Web/DevelopMain.elm
src/Morphir/Compiler.elm
src/Morphir/Compiler/Codec.elm
src/Morphir/Elm/Frontend.elm
src/Morphir/Elm/Frontend/Resolve.elm
src/Morphir/Graph.elm
src/Morphir/IR/FQName.elm
src/Morphir/Type/Class.elm
src/Morphir/Type/Infer.elm
src/Morphir/Type/MetaType.elm

Better error reporting

---

cli/src/Morphir/Web/Insight.elm
package.json

Insight Component in JavaScript API created

---

cli/web/index.html
src/Morphir/Graph/GraphVizBackend.elm
src/Morphir/Visual/ViewIfThenElse.elm

Fix and clean up the custom element and Debug statements. #268

---

src/Morphir/Graph/GraphVizBackend.elm
tests-integration/reference-model/src/Morphir/Reference/Model/Values.elm

Decision tree enhancements. #268

---

cli/src/Morphir/Web/Insight.elm
cli/web/insight.html
cli/web/insight.js
package-lock.json
package.json

Bug Fixes in insight API

---

cli/src/Morphir/Web/DecisionTreeTest.elm
src/Morphir/Visual/Components/DecisionTree.elm
src/Morphir/Visual/ViewIfThenElse.elm
src/Morphir/Visual/ViewValue.elm
tests-integration/reference-model/src/Morphir/Reference/Model/Values.elm

Initial version of pure HTML decision tree. #288

---

src/Morphir/Visual/BoolOperatorTree.elm
src/Morphir/Visual/ViewBoolOperatorTree.elm
src/Morphir/Visual/ViewValue.elm

Skeleton implementation for boolean expression visualization. #291

---

src/Morphir/IR/SDK/Basics.elm
src/Morphir/Visual/Components/DecisionTree.elm
src/Morphir/Visual/Context.elm
src/Morphir/Visual/ViewIfThenElse.elm
src/Morphir/Visual/ViewValue.elm

First working implementation of execution path highlighting. 

---

.gitignore

Fix gitignore.

---

cli/src/Morphir/Web/DevelopMain.elm
src/Morphir/Visual/Components/DecisionTree.elm
src/Morphir/Visual/Context.elm
src/Morphir/Visual/ViewIfThenElse.elm
src/Morphir/Visual/ViewValue.elm

Visualization enhancements

---

src/Morphir/Visual/BoolOperatorTree.elm
src/Morphir/Visual/ViewBoolOperatorTree.elm
tests-integration/reference-model/src/Morphir/Reference/Model/Values.elm

HTML layout for Boolean expressions implemented

---

cli/morphir-elm-make.js
cli/src/Morphir/Elm/CLI.elm

Report unhandled errors properly

---

elm.json
src/Morphir/Elm/Frontend.elm
src/Morphir/IR/FQName.elm
src/Morphir/SDK/Decimal.elm
src/Morphir/Value/Interpreter.elm

Elm Release 8.0.0

---

cli/src/Morphir/Web/DevelopApp.elm

Fix routing. #311

---

cli/elm.json
elm.json
src/Morphir/Elm/Frontend.elm
tests/Morphir/Elm/FrontendTests.elm

Upgraded elm-syntax

---

docs/morphirDocumentation.html

Support Tool for Beginners:
You can paste any Morphir (.elm) file contents or simply write Elm code and it will start defining the functions or definitions it can detect.
You can click on any function (within the input textbox) and it will bring it into view and highlight it.
- Example: Paste src/Morhir/Visual/ViewValue.elm in and click on Value.IfThenElse
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, …

Morphir Documentation - Initial push

---

src/Morphir/Elm/Backend/Codec/DecoderGen.elm
src/Morphir/Elm/Backend/Codec/EncoderGen.elm
src/Morphir/Elm/Frontend.elm
src/Morphir/Elm/Frontend/Resolve.elm
src/Morphir/Graph/Grapher.elm
src/Morphir/IR/SDK/Basics.elm
src/Morphir/IR/SDK/Maybe.elm
src/Morphir/IR/SDK/Month.elm
src/Morphir/IR/SDK/Result.elm
src/Morphir/IR/SDK/StatefulApp.elm
src/Morphir/IR/Type.elm
src/Morphir/IR/Type/Codec.elm
src/Morphir/Scala/Backend.elm
src/Morphir/SpringBoot/Backend.elm
src/Morphir/Type/MetaTypeMapping.elm
tests/Morphir/Elm/Frontend/ResolveTests.elm
tests/Morphir/Elm/FrontendTests.elm
tests/Morphir/Type/InferTests.elm
tests/Morphir/Type/InferTests/BooksAndRecordsTests.elm

Changed constructors from List to Dict. 

---

docs/json-mapping.md

Added JSON mapping docs. #285

---

src/Morphir/IR/SDK/Decimal.elm

Fix bug in mapping Decimal.fromFloat in the IR

---

src/Morphir/Visual/DecisionTable.elm

Added data structure to represent a decision table.

---

cli/morphir-elm-develop.js
cli/src/Morphir/Web/DevelopApp.elm
package.json
src/Morphir/Visual/ViewValue.elm
src/Morphir/Visual/XRayView.elm

Make the web server easier to deploy

---

elm.json

Fix elm.json

---

src/Morphir/IR/SDK/Basics.elm
src/Morphir/Visual/Components/DecisionTree.elm
src/Morphir/Visual/ViewValue.elm

Improvements. #343

---

cli/src/Morphir/Elm/CLI.elm
cli/src/Morphir/Web/DevelopApp.elm
cli/src/Morphir/Web/Insight.elm
src/Morphir/Compiler/Codec.elm
tests/Morphir/Compiler/CodecTests.elm

Version the IR

---

elm.json
src/Morphir/IR/Type.elm
src/Morphir/SDK/DataSet.elm
src/Morphir/SDK/Key.elm
src/Morphir/Value/Interpreter.elm
tests/Morphir/SDK/DataSetTests.elm

Dataset API

---

docs/Insight-README.md

Docs for Insight API created.

---

src/Morphir/SDK/Aggregate.elm

Fixed docs. 

---

src/Morphir/SDK/Aggregate.elm

Fix the docs.

---

src/Morphir/Type/Constraint.elm
src/Morphir/Type/ConstraintSet.elm
src/Morphir/Type/Infer.elm
src/Morphir/Type/MetaType.elm
tests/Morphir/Type/InferTests.elm

Type inference perf improvements. #329

---

cli/elm.json
cli/src/Morphir/Web/DevelopApp.elm
cli/src/Morphir/Web/Insight.elm
elm.json
src/Morphir/Visual/BoolOperatorTree.elm
src/Morphir/Visual/Common.elm
src/Morphir/Visual/Components/AritmeticExpressions.elm
src/Morphir/Visual/Components/DecisionTree.elm
src/Morphir/Visual/Config.elm
src/Morphir/Visual/ViewApply.elm
src/Morphir/Visual/ViewArithmetic.elm
src/Morphir/Visual/ViewBoolOperatorTree.elm
src/Morphir/Visual/ViewField.elm
src/Morphir/Visual/ViewIfThenElse.elm
src/Morphir/Visual/ViewList.elm
src/Morphir/Visual/ViewReference.elm
src/Morphir/Visual/ViewTuple.elm
src/Morphir/Visual/ViewValue.elm

Popup Screen Functionality implemented.

---

cli/cli.js
cli/morphir-elm-make.js
cli/src/Morphir/Elm/CLI.elm
cli/src/Morphir/Elm/DaprCLI.elm
src/Morphir/Elm/Frontend.elm
src/Morphir/Elm/Frontend/Codec.elm
tests/Morphir/Elm/FrontendTests.elm

Added typesOnly option. #384

---

cli/src/Morphir/Web/Insight.elm
docs/Insight-README.md

Major changes in passing arguments to the Insight API.

---

src/Morphir/Type/Infer.elm
src/Morphir/Type/MetaType.elm
src/Morphir/Type/MetaTypeMapping.elm
src/Morphir/Type/Solve.elm
tests-integration/reference-model/morphir.json
tests-integration/reference-model/src/Morphir/Reference/Model/Issues/Issue350.elm
tests/Morphir/Type/InferTests.elm
tests/Morphir/Type/SolveTests.elm

Fix issue caused by meta type variable clash

---

src/Morphir/Type/Class.elm
src/Morphir/Type/Infer.elm
src/Morphir/Type/MetaType.elm
src/Morphir/Type/MetaTypeMapping.elm
src/Morphir/Type/Solve.elm
tests-integration/reference-model/morphir.json
tests-integration/reference-model/src/Morphir/Reference/Model/Issues/Issue349.elm
tests/Morphir/Type/InferTests.elm
tests/Morphir/Type/MetaTypeMappingTests.elm
tests/Morphir/Type/SolveTests.elm

Reproduced and fixed the issue with unifying type aliases.  

---

cli/src/Morphir/Elm/CLI.elm
cli/src/Morphir/Web/DevelopApp.elm
cli/src/Morphir/Web/Insight.elm
src/Morphir/Compiler/Codec.elm
src/Morphir/IR/Distribution/Codec.elm
tests/Morphir/IR/Distribution/CodecTests.elm

Move the versioned distribution codec and expose it. 

---

cli/src/Morphir/Web/DevelopApp.elm

Fix the navigation bug. 

---

src/Morphir/IR/Value.elm
src/Morphir/Scala/Backend.elm
src/Morphir/SpringBoot/Backend.elm
tests-integration/reference-model/morphir.json
tests-integration/reference-model/src/Morphir/Reference/Model/Issues/Issue407.elm

Fix compile error in generated Scala above 22 fields

---

cli/.gitignore
cli/src/Morphir/Web/DebugIR.elm
cli/src/Morphir/Web/TryMorphir.elm
gulpfile.js
src/Morphir/Web/SourceEditor.elm

Initial version of Try Morphir

---

cli/morphir-elm-develop.js

Serve index.html when the URL doesn't match any other known routes.

---

src/Morphir/Visual/DecisionTable.elm
src/Morphir/Visual/ViewPatternMatch.elm
tests-integration/reference-model/src/Morphir/Reference/Model/Issues/DecisionTables.elm

This allows custom types to be visualisable in decision tables

Added support for ConstructorPattern and AsPattern

---

cli/src/Morphir/Web/DevelopApp.elm
cli/src/Morphir/Web/DevelopApp/ModulePage.elm

Morphir web improvements

---

cli/src/Morphir/Web/DevelopApp/ModulePage.elm
src/Morphir/Visual/Components/FieldList.elm
src/Morphir/Visual/ValueEditor.elm
tests-integration/reference-model/morphir.json
tests-integration/reference-model/src/Morphir/Reference/Model/ValueEditors.elm

Cosmetic improvements. More test models.

---

cli/src/Morphir/Web/TryMorphir.elm
package.json

Added the ability to show the JSON version of the IR. 

---

cli/src/Morphir/Web/DevelopApp.elm
cli/src/Morphir/Web/DevelopApp/FunctionPage.elm

Testcase framework functionality Completed

---

cli/src/Morphir/Web/DevelopApp/FunctionPage.elm
src/Morphir/Visual/Theme.elm

Cosmetic improvements

---

tests-integration/reference-model/morphir.json
tests-integration/reference-model/src/Morphir/Reference/Model/Presentations/UKFintechMeetup.elm

Added presentation material.

---

src/Morphir/Elm/Frontend.elm
tests-integration/reference-model/morphir.json
tests-integration/reference-model/src/Morphir/Reference/Model/Issues/Issue450.elm

Reproduced and fixed #450.

---

cli/dev-cli.js
cli/src/Morphir/Elm/DevCLI.elm
gulpfile.js

Simple CLI to run developer tools. #446

---

src/Morphir/Elm/Frontend.elm

Fixed boolean literal patterns. #453

---

src/Morphir/IR.elm
src/Morphir/IR/Type.elm
src/Morphir/Visual/ValueEditor.elm
tests-integration/reference-model/src/Morphir/Reference/Model/ValueEditors.elm

Resolve type aliases before choosing an editor.

---

cli/cli.js
cli/dev-cli.js
cli/src/Morphir/Elm/CLI.elm
cli/src/Morphir/Elm/Common.elm
cli/src/Morphir/Elm/DevCLI.elm
cli/src/Morphir/Web/DevelopApp.elm
src/Morphir/Visual/DecisionTable.elm

First Version of Native.Function wrappers for all functions in the SDK implemented. #446

---

src/Morphir/IR/SDK/Basics.elm
src/Morphir/IR/SDK/List.elm
src/Morphir/Value/Native.elm

Improvements on the Native Function API

---

src/Morphir/IR/Value.elm
src/Morphir/Value/Native/Comparable.elm
src/Morphir/Value/Native/Eq.elm
tests/Morphir/Value/Native/EqTests.elm

Helpers for correct native implementations. #446

---

src/Morphir/IR/SDK/Char.elm

Fixed type signatures in Char module

---

cli/cli.js
src/Morphir/Visual/XRayView.elm

Quick fix for make command. Cosmetic changes on XRay view.

---

src/Morphir/Type/Infer.elm
tests-integration/reference-model/src/Morphir/Reference/Model/ValueEditors.elm

Reproduced and fixed issue #462

---

src/Morphir/Visual/ViewPatternMatch.elm

Fixed highlighting logic following fully matched rows.

---

src/Morphir/Visual/ValueEditor.elm
tests-integration/reference-model/src/Morphir/Reference/Model/ValueEditors.elm

Reproduced and fixed issue #466

---

cli/src/Morphir/Web/DevelopApp.elm
cli/src/Morphir/Web/DevelopApp/FunctionPage.elm
cli/src/Morphir/Web/DevelopApp/ModulePage.elm
src/Morphir/Visual/Theme.elm

Use a button instead of a link. #471

---

src/Morphir/Graph/CypherBackend.elm
src/Morphir/Visual/ViewPatternMatch.elm

Fixed logic to accept text editor values for non-variable types

---

src/Morphir/Elm/Frontend.elm

Frontend Issue Fixed

---

cli/cli.js
cli/morphir-elm-test.js
cli/morphir-elm.js
cli/src/Morphir/Elm/CLI.elm
package-lock.json
package.json

Added a new CLI command that runs all test scenarios and fails if any of them is producing unexpected results #480

---

src/Morphir/Elm/Frontend.elm
src/Morphir/Visual/ValueEditor.elm

Fix error reporting for the generic editor.

---

src/Morphir/Visual/ValueEditor.elm
tests-integration/reference-model/src/Morphir/Reference/Model/ValueEditors.elm

Maybe editor

---

cli/src/Morphir/Web/DevelopApp/FunctionPage.elm
cli/src/Morphir/Web/DevelopApp/ModulePage.elm
cli/src/Morphir/Web/Insight.elm
src/Morphir/Visual/Components/DecisionTable.elm
src/Morphir/Visual/Config.elm
src/Morphir/Visual/ViewPatternMatch.elm
src/Morphir/Visual/ViewValue.elm
tests-integration/reference-model/src/Morphir/Reference/Model/Issues/DecisionTables.elm

Additions to DecisionTable highlight logic

---

src/Morphir/Metadata.elm

Refactoring graph stuff into Metadata for simpler access

---

src/Morphir/Value/Interpreter.elm
tests-integration/reference-model/morphir.json
tests-integration/reference-model/src/Morphir/Reference/Model/Issues/Issue493.elm

Reproduced issue and fixed evaluator. #493

---

cli/src/Morphir/Elm/CLI.elm
package.json
src/Morphir/IR/SDK/List.elm
src/Morphir/IR/SDK/Maybe.elm
src/Morphir/IR/Type/DataCodec.elm
tests-integration/reference-model/morphir.json
tests-integration/reference-model/src/Morphir/Reference/Model/Insight/UseCase2.elm
tests-integration/reference-model/src/Morphir/Reference/Model/Values.elm

Minor Bug Fixes

---

gulpfile.js

Update morphir-jvm version.

---

src/Morphir/IR/SDK/Basics.elm
src/Morphir/Value/Error.elm
src/Morphir/Value/Native.elm
tests/Morphir/Value/InterpreterTests.elm

SDK Basics Functionality Implemented completely #499.

---

src/Morphir/TypeScript/AST.elm
src/Morphir/TypeScript/Backend.elm
src/Morphir/TypeScript/PrettyPrinter.elm
tests/Morphir/TypeScript/BackendTests.elm

Initial skeleton of the TypeScript backend. #503

---

src/Morphir/IR/SDK.elm
src/Morphir/IR/SDK/ResultList.elm
src/Morphir/SDK/ResultList.elm

Initial version of ResultList module. #508

---

elm.json

closes #508, #511
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF …

Add missing exposed modules. 

---

cli/morphir-elm-test.js

This is a proposed fix for https://github.com/finos/morphir-elm/issues/521
There may be a better way to do this :)
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS …

Display errors in `morphir-elm test` correctly

---

elm.json
src/Morphir/SDK/Validate.elm

Added validation module to SDK.

---

src/Morphir/IR/Value.elm
src/Morphir/Relational/Backend.elm
src/Morphir/Relational/IR.elm
src/Morphir/Scala/Spark/API.elm
src/Morphir/Scala/Spark/Backend.elm
src/Morphir/Value/Refactor.elm
tests-integration/reference-model/src/Morphir/Reference/Model/SparkTests.elm
tests-integration/reference-model/target/reference-model-scala/build.sbt

Relational backend enhancements

---

src/Morphir/IR/Value.elm

Added missing type annotation for morphir compiler

---

elm.json
src/Morphir/Metadata.elm

Exposes the Metadata module for integrating metadata functionality.
> …

Exposing Metadata to API

---

gulpfile.js
src/Morphir/Metadata.elm

Check to verify correct documentation. 

---

src/Morphir/Value/Interpreter.elm
tests-integration/reference-model/morphir.json
tests-integration/reference-model/src/Morphir/Reference/Model/Issues/Issue571.elm

Reproduce and fix #571

---

gulpfile.js

Turn of Scala tests because they are causing issues with publishing

---

cli/src/Morphir/Web/TryMorphir.elm
src/Morphir/Elm/Frontend.elm
src/Morphir/Elm/Frontend/Codec.elm
tests/Morphir/Elm/FrontendTests.elm

Make "exposedModules" optional and expose all modules when it's not set.

---

cli/elm.json
cli/src/Morphir/Web/DevelopApp.elm
elm.json

Cosmetic changes on Morphir Web.

---

cli/src/Morphir/Web/DevelopApp.elm

Small cosmetic improvements.

---

src/Morphir/File/FileChanges/Codec.elm

Added codec for file changes.

---

src/Morphir/Type/Constraint.elm
src/Morphir/Type/ConstraintSet.elm
src/Morphir/Type/Infer.elm
src/Morphir/Type/Solve.elm

The main change is that we are not re-applying all the previous solutions anymore.  #485
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; …

Performance improvement that speeds up solving

---

src/Morphir/Scala/Backend.elm
tests-integration/reference-model/src/Morphir/Reference/Model/Issues/Issue600.elm

Fixed code generator. 

---

src/Morphir/Elm/ModuleName.elm
src/Morphir/IR/Repo.elm

initial implementation of orderElmModuleByDependency & insertModule functions

---

cli/elm.json
cli/src/Morphir/Web/DevelopApp.elm
cli/src/Morphir/Web/DevelopApp/Common.elm
src/Morphir/Visual/Theme.elm

- paint selected concept's background
- eliminate some code duplication
- fix duplicate selection in case of same name
- add search for definitions, plus small ui changes
- alphabetical ordering of definitions
- filter by values or types
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, …

ui changes

---

src/Morphir/IR/Repo.elm

insertType function partially completed

---

cli/src/Morphir/Web/DevelopApp.elm
src/Morphir/Visual/Theme.elm

- show originating module in definition list
- make definition list prettier
> …

Prettier and more informative definition list

---

cli/morphir-dapr.js
cli/morphir-elm-develop.js
cli/morphir-elm-gen.js
cli/morphir-elm-make.js
cli/morphir-elm-test.js

Fix commander option lookup. 

---

src/Morphir/IR/Repo/Codec.elm

type already exist error handled in repo codec

---

cli/src/Morphir/Web/DevelopApp.elm
cli/src/Morphir/Web/DevelopApp/ModulePage.elm

- show originating module in definition list
- make definition list prettier
- display definition details on main page
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; …

display definition details on the main page

---

.gitignore
redistributable/SpringBoot/pom.xml

Add missing license and gitignore entry

---

elm.json
src/Morphir/Elm/IncrementalResolve.elm
src/Morphir/IR/Repo.elm

Incremental resolver

---

.gitignore
elm.json
src/Morphir/SDK/LocalTime.elm

elm-package publishing

---

.github/workflows/npm-publish.yml

github action to publish to npm added

---

src/Morphir/Dependency/DAG.elm
src/Morphir/IR/Repo.elm

changed DAG type and implementation

---

tests/Morphir/Elm/IncrementalFrontendTests.elm

added test for IncrementalFrontend/parseElmModules

---

.github/workflows/npm-publish.yml

build command inserted into github workflow

---

.gitignore
package-lock.json
package.json

enabled elm coverage for tests

---

cli/src/Morphir/Web/DevelopApp.elm
src/Morphir/Visual/Theme.elm

better modules menu

---

gulpfile.js
package.json

Add build to gulpfile

---

src/Morphir/Dependency/DAG.elm
src/Morphir/Elm/IncrementalFrontend.elm
src/Morphir/Elm/IncrementalFrontend/Codec.elm

Order types by dependency

---

src/Morphir/IR/SDK.elm
src/Morphir/IR/SDK/LocalTime.elm

Quick fix to include LocalTime in the SDK.

---

cli/src/Morphir/Elm/DevCLI.elm
cli/src/Morphir/Web/DevelopApp.elm
cli/src/Morphir/Web/DevelopApp/ModulePage.elm
cli/src/Morphir/Web/TryMorphir.elm
src/Morphir/Elm/Frontend.elm
src/Morphir/Graph/Grapher.elm
src/Morphir/IR.elm
src/Morphir/IR/Documented/Codec.elm
src/Morphir/IR/Documented/CodecV1.elm
src/Morphir/IR/Module.elm
src/Morphir/IR/Module/Codec.elm
src/Morphir/IR/Module/CodecV1.elm
src/Morphir/IR/SDK/Common.elm
src/Morphir/IR/SDK/Regex.elm
src/Morphir/Scala/Backend.elm
src/Morphir/SpringBoot/Backend.elm
src/Morphir/Type/Infer.elm
src/Morphir/Visual/XRayView.elm
tests/Morphir/Elm/Frontend/ResolveTests.elm
tests/Morphir/Elm/FrontendTests.elm

add documentation to value types, with placeholder in the SDK

---

cli/src/Morphir/Web/DevelopApp.elm

Display value docs on the ui

---

src/Morphir/Elm/IncrementalFrontend.elm
src/Morphir/Elm/IncrementalFrontend/Codec.elm
src/Morphir/Elm/IncrementalResolve.elm
src/Morphir/Elm/IncrementalResolve/Codec.elm

Resolve type names

---

docs/publishing.md

Update publishing documentation

---

cli/src/Morphir/Web/DevelopApp.elm

reorganize module menu

---

src/Morphir/Type/Infer/Codec.elm
src/Morphir/Type/Solve/Codec.elm

Added missing codecs.

---

elm.json
src/Morphir/Elm/Frontend.elm
src/Morphir/Type/Infer.elm

Remove all Debug references to enable publishing.

---

src/Morphir/Dependency/DAG.elm
tests/Morphir/Dependency/DAGTests.elm

updated shiftTransitively to break endless recursion

---

src/Morphir/Dependency/DAG.elm
src/Morphir/Elm/IncrementalFrontend.elm
src/Morphir/IR/Repo.elm
tests/Morphir/IR/Repo/RepoTest.elm

Updated Repo with docs and some other changes

---

cli/src/Morphir/Web/DevelopApp.elm
cli/src/Morphir/Web/DevelopApp/Common.elm
cli/src/Morphir/Web/DevelopApp/ModulePage.elm
cli/src/Morphir/Web/TryMorphir.elm
src/Morphir/Visual/Components/TreeLayout.elm
src/Morphir/Visual/ViewValue.elm
src/Morphir/Visual/XRayView.elm

url based navigation

---

cli2/cli.ts
cli2/src/Morphir/Elm/CLI.elm
src/Morphir/Elm/Frontend/Mapper.elm
src/Morphir/Elm/IncrementalFrontend.elm
src/Morphir/Elm/IncrementalFrontend/Codec.elm
src/Morphir/Elm/IncrementalResolve.elm
src/Morphir/File/FileChanges.elm
src/Morphir/IR/Package.elm
src/Morphir/IR/Repo.elm
src/Morphir/IR/Repo/Codec.elm
tests/Morphir/Elm/IncrementalFrontendTests.elm

Granular incremental processing

---

src/Morphir/Dependency/DAG.elm

Tail-recursive version of reachability

---

src/Morphir/IR/Repo.elm
src/Morphir/IR/Type.elm
tests/Morphir/IR/Repo/RepoTest.elm

refactored insertValue and updating moduleDependency while inserting values

---

cli/src/Morphir/Web/DevelopApp.elm
cli/src/Morphir/Web/Graph/DependencyGraph.elm
cli/src/Morphir/Web/Graph/Graph.elm
cli/web/graph.html
cli/web/graph.js
cli/web/index.js
gulpfile.js
package-lock.json
package.json

Dependency visual graph

---

cli/src/Morphir/Web/DevelopApp.elm

Add some documentation to DevelopApp

---

cli/src/Morphir/Web/DevelopApp.elm
cli/src/Morphir/Web/Graph/DependencyGraph.elm

button to hide definition list + some refactoring

---

src/Morphir/Scala/Backend.elm

Curry constructor arguments as needed. 

---

cli/src/Morphir/Web/DevelopApp.elm

Fix scroll issue

---

cli/src/Morphir/Web/DevelopApp.elm

reintroducing insight view

---

src/Morphir/Scala/Backend.elm
src/Morphir/Scala/JSONBackend.elm
src/Morphir/Scala/PrettyPrinter.elm
tests/Morphir/Scala/JSONBackendTests.elm

Beginnings of the Scala JSON backend.

---

src/Morphir/Elm/IncrementalFrontend.elm
src/Morphir/IR/Repo.elm
src/Morphir/IR/Repo/Codec.elm
tests-integration/cli2/cli2.test.ts
tests-integration/cli2/ir-utils.ts

wip; update types and values intially completed

---

cli/src/Morphir/Web/DevelopApp.elm
cli/src/Morphir/Web/DevelopApp/Common.elm
cli/src/Morphir/Web/DevelopApp/FunctionPage.elm
src/Morphir/Visual/Components/FieldList.elm

Testing UI

---

.gitignore
package.json

added missing js file

---

docs/developers-guide/files/publishing.md

renamed master to main

---

package.json

Fix NPM package

---

cli/src/Morphir/Web/DevelopApp.elm

Load and delete functionality for test cases

---

src/Morphir/IR/Attribute.elm

Attributes

---

src/Morphir/SDK/Constraints.elm

Basic constraints for string, int and decimal

---

src/Morphir/IR/Attribute.elm
src/Morphir/IR/NodePath.elm

Initial version of attributes

---

cli/src/Morphir/Web/DevelopApp.elm
src/Morphir/Correctness/Codec.elm
src/Morphir/Correctness/Test.elm
src/Morphir/Value/Interpreter.elm
src/Morphir/Visual/Theme.elm
tests/Morphir/TestCasesJson.elm

making the testing UI prettier + design fixes

---

gulpfile.js
tests-integration/build.sc
tests-integration/mill

spark setup fix

---

docs/README.md
docs/developers-guide/README.md
docs/developers-guide/files/scala-json-codecs-backend.md

Updated Links in the Documentation Home

---

package-lock.json
package.json

Bump NPM package version

---

.github/workflows/nodejs.yml

Publish package improvements

---

src/Morphir/Elm/IncrementalResolve.elm

Added basic types to default SDK imports

---

cli2/FileChanges.ts
cli2/cli.ts

avoid overwrite when there is no fileChange

---

.github/workflows/nodejs.yml

publish action find path issue fix

---

src/Morphir/Visual/Components/FieldList.elm
src/Morphir/Visual/ValueEditor.elm

show valueditor types + grid editor fix

---

src/Morphir/Spark/AST.elm
tests-integration/reference-model/src/Morphir/Reference/Model/SparkTests.elm

minimal support for let definitions

---

cli/src/Morphir/Elm/Target.elm
cli2/cli.ts
cli2/morphir.ts
cli2/src/Morphir/Elm/CLI.elm
src/Morphir/FeatureMetrics/Backend.elm
src/Morphir/Stats/Backend.elm

Setup tool to collect Features from a morphir IR.

---

cli/src/Morphir/Web/DevelopApp.elm
cli/src/Morphir/Web/Insight.elm
src/Morphir/IR/Type/DataCodec.elm
src/Morphir/Visual/ViewApply.elm
src/Morphir/Visual/ViewList.elm
src/Morphir/Visual/ViewLiteral.elm
src/Morphir/Visual/ViewRecord.elm
src/Morphir/Visual/ViewValue.elm

update visualisations related to 'Record' types

---

src/Morphir/Elm/IncrementalFrontend.elm

Tree shaking before module process

---

src/Morphir/Elm/IncrementalResolve.elm

Fixed import collision issue.

---

src/Morphir/Elm/IncrementalResolve.elm

Add missing change for incremental build fix

---

src/Morphir/Elm/IncrementalFrontend.elm

Fix exposedModules only including updates & inserts

---

cli2/src/Morphir/Elm/CLI.elm
src/Morphir/Elm/IncrementalFrontend.elm

Fix tree shaking.

---

src/Morphir/Elm/IncrementalFrontend.elm
src/Morphir/Elm/IncrementalFrontend/Codec.elm

removed some unused error in IncrementalFrontend 

---

cli/src/Morphir/Web/DevelopApp.elm
src/Morphir/Visual/Components/DecisionTable.elm
src/Morphir/Visual/Components/FieldList.elm
src/Morphir/Visual/ViewApply.elm
src/Morphir/Visual/ViewLambda.elm
src/Morphir/Visual/ViewLiteral.elm
src/Morphir/Visual/ViewValue.elm

visualizations for lambdas and field functions

---

package.json
src/Morphir/Elm/IncrementalFrontend.elm
src/Morphir/Elm/IncrementalFrontend/Mapper.elm
src/Morphir/IR/Repo.elm
tests-integration/cli/cli.test.ts
tests-integration/cli2-qa-test/cli2QA.test.ts
tests-integration/cli2/cli2.test.ts
tests-integration/ts-test-utils/ir-utils.ts
tests/Morphir/Elm/IncrementalFrontendTests.elm
tests/Morphir/IR/Repo/RepoTest.elm

add type and value documentation on insert

---

src/Morphir/Elm/Frontend.elm
src/Morphir/Elm/IncrementalFrontend/Mapper.elm
src/Morphir/Graph/Grapher.elm
src/Morphir/IR.elm
src/Morphir/IR/Type/DataCodec.elm
src/Morphir/IR/Value.elm
src/Morphir/IR/Value/Codec.elm
src/Morphir/IR/Value/CodecV1.elm
src/Morphir/Relational/Backend.elm
src/Morphir/Scala/Backend.elm
src/Morphir/Spark/AST.elm
src/Morphir/Stats/Backend.elm
src/Morphir/Type/Infer.elm
src/Morphir/Value/Interpreter.elm
src/Morphir/Visual/ValueEditor.elm
src/Morphir/Visual/ViewList.elm
src/Morphir/Visual/ViewRecord.elm
src/Morphir/Visual/ViewValue.elm
src/Morphir/Visual/XRayView.elm
tests/Morphir/Elm/FrontendTests.elm
tests/Morphir/IR/ValueFuzzer.elm
tests/Morphir/IR/ValueTests.elm
tests/Morphir/TestCasesJson.elm
tests/Morphir/Type/InferTests.elm

Refactor Value.Record and Value.RecordUpdate to have Dict as parameter instead of List

---

elm.json

Bump elm package version

---

src/Morphir/Visual/ViewList.elm
src/Morphir/Visual/ViewValue.elm

Fix displaying of type aliases

---

.github/workflows/nodejs.yml

Move Elm publishing into the build job to fix it.

---

cli2/cli.ts
cli2/morphir-make.ts

added a build incrementally flag

---

elm.json
src/Morphir/IR/Documented.elm

Added Documented

---

docs/developers-guide/files/spark-backend.md
src/Morphir/Spark/AST.elm
tests-integration/spark/model/src/SparkTests/FunctionTests.elm
tests-integration/spark/test/src/SparkJobsTest.scala
tests-integration/spark/test/src/SparkTypeTest.scala

Fix handling of Floats, enums and add more tests for 'case' functionality

---

cli2/morphir-stats.ts
src/Morphir/Stats/Backend.elm

added missing morphir-stats ts file

---

tests-integration/reference-model/src/Morphir/Reference/Model/Sample/Rules/Income/Antique.elm

list.map added to LCR simulation rules

---

package-lock.json
package.json
tests-integration/reference-model/src/Morphir/Reference/Model/Sample/Rules/Income/Antique.elm

Publish to npm

---

package-lock.json
package.json

added morphir-stats.js to package.json

---

src/Morphir/Scala/AST.elm

Add some documentation for the Scala Value type

---

docs/contribution-guide/README.md

Document a git pre-commit hook for elm-format

---

docs/developers-guide/files/spark-backend.md
src/Morphir/Spark/AST.elm
src/Morphir/Spark/Backend.elm
tests-integration/spark/model/src/SparkTests/ListMemberTests.elm
tests-integration/spark/test/src/ListMemberTests.scala

Spark backend List.member to Spark isin() code generation

---

src/Morphir/Elm/IncrementalFrontend.elm
src/Morphir/IR/Repo.elm

fixed repo moduleDAG having every moduleName as an incoming edge

---

cli/src/Morphir/Web/DevelopApp.elm
cli/src/Morphir/Web/DevelopApp/Common.elm
cli/src/Morphir/Web/TryMorphir.elm
src/Morphir/Visual/Common.elm
src/Morphir/Visual/Components/DecisionTable.elm
src/Morphir/Visual/Components/DecisionTree.elm
src/Morphir/Visual/ViewApply.elm
src/Morphir/Visual/ViewIfThenElse.elm
src/Morphir/Visual/ViewPatternMatch.elm
src/Morphir/Visual/ViewValue.elm

- make isnightView the default
- make model functions used in other model functions clickable
- fix issues with highlight sync between decision tables and decision
trees
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED …

insight view changes & fixes

---

docs/developers-guide/files/spark-backend.md
src/Morphir/Spark/AST.elm
tests-integration/spark/model/src/SparkTests/FunctionTests.elm
tests-integration/spark/test/src/SparkJobsTest.scala

NOTE: This PR is based on #804 and shouldn't be merged until that one has.
> …

Spark: Add support for aggregating List.maximum

---

src/Morphir/IR/SDK.elm
src/Morphir/IR/SDK/Aggregate.elm
src/Morphir/IR/SDK/Key.elm
src/Morphir/SDK/Aggregate.elm

to allow modelers to be more declarative when building aggregations.
> …

Added groupBy and aggregate functions 

---

gulpfile.js

Changed morphir-jvm to current version

---

package-lock.json
package.json

Morphir jvm version update

---

.github/workflows/nodejs.yml
package-lock.json
package.json

publishing error fixes

---

docs/developers-guide/README.md

Updated docs link for Jonathan's Spark documentation

---

.github/workflows/nodejs.yml
docs/contribution-guide/publishing.md
package-lock.json
package.json

npm publish automation removed + publishing docs reverted to old

---

docs/contribution-guide/verification.md

docs for verifying a release

---

cli/src/Morphir/Web/Graph/DependencyGraph.elm
cli/src/Morphir/Web/Graph/Graph.elm
tests-integration/reference-model/src/Morphir/Reference/Model/Issues/UIDependency.elm

fixed isssue with UI graph dependency

---

src/Morphir/SDK/List.elm

Expose join functions

---

tests-integration/spark/model/src/SparkTests/FunctionTests.elm

Fix a broken test

---

src/Morphir/IR/SDK/List.elm
src/Morphir/SDK/List.elm
tests-integration/reference-model/morphir-tests.json
tests-integration/reference-model/src/Morphir/Reference/Model/Relational.elm
tests/Morphir/SDK/ListTests.elm

Add join operators

---

Dockerfile
cli/web/graph.html
cli/web/index.html
docs/developers-guide/files/morphirDocumentation.html
server/Dockerfile

Docker file finding solution

---

cli/assets/DaprAppShell.js
cli/morphir-elm-develop.js
package-lock.json
package.json
server/server.js

Csrf token impl

---

src/Morphir/Visual/Components/DecisionTable.elm
src/Morphir/Visual/ViewPatternMatch.elm

fix decision table hover values

---

cli/elm.json
cli2/elm.json
src/Morphir/IR/Literal/Codec.elm
src/Morphir/IR/Literal/CodecV1.elm
src/Morphir/IR/SDK.elm
src/Morphir/IR/SDK/LocalDate.elm
src/Morphir/IR/Type.elm
src/Morphir/IR/Type/Codec.elm
src/Morphir/IR/Type/CodecV1.elm
src/Morphir/IR/Type/DataCodec.elm
src/Morphir/SDK/LocalDate.elm
src/Morphir/Stats/Backend.elm
src/Morphir/Type/Cardinality.elm
src/Morphir/Value/Error.elm
src/Morphir/Value/Native.elm
src/Morphir/Visual/ValueEditor.elm
tests-integration/reference-model/src/Morphir/Reference/Model/SDK/LocalDate.elm
tests-integration/reference-model/src/Morphir/Reference/Model/Values.elm
tests/Morphir/IR/Type/DataCodecTests.elm
tests/Morphir/IR/TypeFuzzer.elm
tests/Morphir/IR/ValueFuzzer.elm

Added Derived Type Spec

---

cli/morphir-elm-develop.js

csrf removed

---

src/Morphir/Visual/Components/DecisionTree.elm

change decision tree layout

---

src/Morphir/Scala/PrettyPrinter.elm
tests/Morphir/Scala/JSONBackendTests.elm

added parenthesis around scala lambdas

---

src/Morphir/Visual/Components/DecisionTree.elm
src/Morphir/Visual/ViewIfThenElse.elm
src/Morphir/Visual/ViewValue.elm

change DecisionTree to display simple 'case ..of'-s

---

.github/workflows/nodejs.yml

Finos security fixes

---

tests-integration/spark/model/elm.json
tests-integration/spark/model/src/SparkTests/Rules/Income/Antique.elm

Improve spark example

---

src/Morphir/Visual/ViewApply.elm

fix insight navigation bug

---

cli/src/Morphir/Elm/CLI.elm
morphir.json
src/Morphir/Elm/Frontend/Resolve.elm

Small fixes to make morphir-elm make work on morphir.

---

cli/src/Morphir/Web/DevelopApp.elm
cli/src/Morphir/Web/Insight.elm
cli/web/insight.html
src/Morphir/Visual/Common.elm
src/Morphir/Visual/Components/DrillDownPanel.elm
src/Morphir/Visual/Components/VisualizationState.elm
src/Morphir/Visual/Config.elm
src/Morphir/Visual/EnrichedValue.elm
src/Morphir/Visual/ViewApply.elm
src/Morphir/Visual/ViewIfThenElse.elm
src/Morphir/Visual/ViewValue.elm
tests-integration/reference-model/src/Morphir/Reference/Model/TestModel/testing.elm

drilldown functionality

---

src/Morphir/Visual/Components/DrillDownPanel.elm
src/Morphir/Visual/Components/TreeLayout.elm
src/Morphir/Visual/ViewApply.elm

better header for opened drilldowns

---

cli/src/Morphir/Web/DevelopApp.elm
src/Morphir/Visual/Components/DrillDownPanel.elm
src/Morphir/Visual/Theme.elm
src/Morphir/Visual/ViewApply.elm

reduce default font size, and some insight spacing

---

src/Morphir/Type/Infer.elm
src/Morphir/Type/MetaType.elm

Fix stack overflow in type inference

---

cli/src/Morphir/Web/DevelopApp.elm
src/Morphir/Visual/Components/DrillDownPanel.elm
src/Morphir/Visual/Components/SectionComponent.elm
src/Morphir/Visual/Components/SelectableElement.elm
src/Morphir/Visual/Components/TabsComponent.elm
src/Morphir/Visual/Theme.elm
src/Morphir/Visual/ViewValue.elm

New components & layout changes

---

cli/morphir-elm-develop.js
cli/src/Morphir/Web/DevelopApp.elm
docs/users-guide/Custom Attributes.md
src/Morphir/CustomAttribute/Codec.elm
src/Morphir/CustomAttribute/CustomAttribute.elm
src/Morphir/IR/NodeId.elm
tests-integration/reference-model/attributemodel/morphir.json
tests-integration/reference-model/attributemodel/src/attributedef.elm
tests-integration/reference-model/attributes.conf.json
tests-integration/reference-model/attributes/sensitivity.ir.json
tests-integration/reference-model/attributes/test-id-1.json
tests-integration/reference-model/attributes/test-id-2.json

Custom attributes edit values

---

elm.json
src/Morphir/SDK/Decimal.elm
tests/Morphir/IR/ValueFuzzer.elm
tests/Morphir/SDK/DecimalTests.elm
tests/Morphir/SDK/NumberTests.elm
tests/Morphir/TestUtils.elm

Upgrade elm-test version and replace changed functions.

---

cli/src/Morphir/Web/DevelopApp.elm
src/Morphir/Visual/Components/SelectableElement.elm
src/Morphir/Visual/Components/TreeViewComponent.elm
tests-integration/reference-model/attributes/test-id-1.json

Tree-tree-view-component

---

src/Morphir/IR/SDK/Aggregate.elm
src/Morphir/SDK/Aggregate.elm
tests/Morphir/SDK/AggregateTests.elm

Add aggregateMap4 function

---

cli/src/Morphir/Web/Insight.elm
src/Morphir/Visual/Components/DrillDownPanel.elm

Drilldown bug fixes

---

src/Morphir/IR/Name.elm
src/Morphir/IR/Value.elm
src/Morphir/Visual/ViewApply.elm
src/Morphir/Visual/ViewValue.elm
tests/Morphir/IR/ValueTests.elm

rewrite maybe map to pattern match

---

.gitignore
lib/main.ts

Example TS API usage

---

cli/src/Morphir/Web/InsightTestApp.elm
cli/web/insight-test.html
package.json

Insight test app

---

cli/src/Morphir/Web/DevelopApp.elm
package-lock.json
package.json
src/Morphir/Visual/ViewApply.elm
src/Morphir/Visual/ViewValue.elm

fix drilldown on references & reorder insight sections

---

cli/morphir-elm-develop.js
cli/src/Morphir/Web/DevelopApp.elm

Catch all exceptions and return {} if there is an issue while reading attributes.
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR …

Fix 500 error

---

docs/developers-guide/cadl-docs/README.md

morphir type mappings to cadl type documentation

---

package.json

Add missing file in NPM package

---

cli/src/Morphir/Web/TryMorphir.elm
src/Morphir/Type/Infer.elm
tests/Morphir/Type/InferTests.elm
tests/Morphir/Type/InferTests/Issue889.elm
tests/Morphir/Type/InferTests/RecordFieldAccessTests.elm

Type inference fix

---

src/Morphir/Scala/Feature/Core.elm

TypeAscripted partial lambdas

---

cli/morphir-elm-develop.js

Removed redundant code from morphir-elm-develop.js

---

src/Morphir/Visual/Components/DrillDownPanel.elm
src/Morphir/Visual/DesignSystemApp.elm
src/Morphir/Visual/Theme.elm
src/Morphir/Visual/ViewApply.elm

Here are some screenshots of how this changes the appearance of the drill-down:
|   | Before | After |
| - | - | - |
| Expanded | ![Screenshot 2023-01-09 133157](https://user-images.githubusercontent.com/60483498/211310632-722f2b70-a383-4575-82a1-b6cc517c3ab3.png) | ![Screenshot 2023-01-09 133245](https://user-images.githubusercontent.com/60483498/211310946-5b59b563-4ef4-4a56-a313-dda56869f263.png) |
| Collapsed | ![Screenshot 2023-01-09 133744](https://user-images.githubusercontent.com/60483498/211311039-09bbccf9-7259-42e6-9ba4-f2a934fdca9b.png) | ![Screenshot 2023-01-09 133806](https://user-images.githubusercontent.com/60483498/211311067-8bb5fda9-b904-4359-b838-98a1229c997f.png) |
> THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE TERMS OF THE CCLA DATED 2017-11-07 WITH …

Alternative styling for drill-down.

---

tests-integration/reference-model/src/Morphir/Reference/Model/Issues/Issue969.elm

reproduced issue 969 in reference model

---

docs/developers-guide/json-codec-docs/README.md

documentation for json codec backend

---

src/Morphir/IR/Type.elm

Added missing documentation.

---

cli/src/Morphir/Web/DevelopApp.elm
src/Morphir/Visual/Components/DecisionTree.elm
src/Morphir/Visual/Components/FieldList.elm
src/Morphir/Visual/Components/InputComponent.elm
src/Morphir/Visual/Components/SectionComponent.elm
src/Morphir/Visual/Components/SelectableElement.elm
src/Morphir/Visual/Components/TabsComponent.elm
src/Morphir/Visual/Components/TreeViewComponent.elm
src/Morphir/Visual/Theme.elm
src/Morphir/Visual/ValueEditor.elm

tab navigation and focus indicators

---

gulpfile.js

update morphir-jvm version to be downloaded

---

cli/cli.js

filesToDelete return type changed from tuple to path

---

cli/morphir-elm-develop.js

Make the code tolerate missing config better. #988

---

src/Morphir/Scala/Feature/Core.elm

map Private to public

---

tests/Morphir/Scala/Feature/CoreTests.elm

added tests for private modules

---

redistributable/Cadl/sdk/package.json
redistributable/Cadl/sdk/sdk.cadl

cadl sdk package

---

src/Morphir/IR/Value.elm
src/Morphir/Visual/ViewList.elm

remove some debug code

---

cli/cli.js
gulpfile.js

Fix Issue #1012

---

cli/src/Morphir/Web/DevelopApp.elm
src/Morphir/Visual/Theme.elm

more sophisticated HTTP error display

---

src/Morphir/Visual/ViewApply.elm

put parameters first if function starts with "is"

---

src/Morphir/Visual/Components/DecisionTable.elm
src/Morphir/Visual/Components/DecisionTree.elm

decision tree layout heuristics

---

cli2/morphir-generate-test-data.ts

Added missing ts file 

---

src/Morphir/Visual/ViewValue.elm

Fix duplicate variable value popups

---

package.json

added lib to files in package.json

---

src/Morphir/Visual/ViewPatternMatch.elm

Don't highlight pattern match on default input

---

redistributable/TypeScript/morphir/internal/Codecs.ts

fix codec bug

---

cli/src/Morphir/Web/DevelopApp.elm
src/Morphir/IR/Repo.elm

Entrypoint indicators 

---

src/Morphir/Scala/Feature/Codec.elm
tests/Morphir/Scala/Feature/CodecTests.elm

Structural types generated for known record types codec bug fix

---

cli/web/index.html

dependency graph display fixed

---

src/Morphir/IR/Repo.elm

Only show entrypoints that call others

---

src/Morphir/IR/NodeId.elm

fix bug in nodeID from String conversion

---

src/Morphir/Visual/ValueEditor.elm

fix for custom type value editor

---

cli/src/Morphir/Web/DevelopApp.elm
src/Morphir/Correctness/Codec.elm
src/Morphir/IR/SDK/Dict.elm
src/Morphir/IR/SDK/LocalDate.elm
src/Morphir/IR/Type/DataCodec.elm
src/Morphir/Value/Error.elm
src/Morphir/Visual/ValueEditor.elm

fix issues with encoding / decoding

---

src/Morphir/IR/Value.elm
src/Morphir/Visual/ViewApply.elm

Replace variables with input values in drilldowns

---

cli/src/Morphir/Web/Editor.elm
cli/src/Morphir/Web/InsightTestApp.elm

Fixed bugs from IR -> Distribution migration

---

.gitignore
cli2/morphir-init.ts
cli2/morphir.ts
package-lock.json
package.json

morphir init

---

src/Morphir/IR/NodeId.elm

Fixed bug with Module decoration

---

src/Morphir/Visual/ViewValue.elm

Fix wrong conf variable passed when unnesting let defs

---

src/Morphir/Visual/ViewApply.elm
src/Morphir/Visual/ViewLambda.elm
src/Morphir/Visual/ViewValue.elm

new visualisation for map, filter, filterMap

---

src/Morphir/Visual/Components/DecisionTable.elm
src/Morphir/Visual/Components/InputComponent.elm
src/Morphir/Visual/ValueEditor.elm

fix input width and Enum capitalisation problems

---

cli/morphir-elm-make.js
cli2/cli.ts
cli2/morphir-make.ts

Add option for indentation and make no indentation the default. 

---

gulpfile.js

Upgrade morphir-jvm version to latest.

---

src/Morphir/IR/Type.elm

expose DerivedTypeSpecificationDetails

---

tests-integration/decoration-model/elm.json
tests-integration/decoration-model/morphir.json
tests-integration/decoration-model/src/Morphir/Decoration/Model/Composites.elm
tests-integration/decoration-model/src/Morphir/Decoration/Model/Database.elm
tests-integration/decoration-model/src/Morphir/Decoration/Model/JsonSchema.elm
tests-integration/decoration-model/src/Morphir/Decoration/Model/NumberConstraints.elm
tests-integration/decoration-model/src/Morphir/Decoration/Model/PrivacyControl.elm
tests-integration/decoration-model/src/Morphir/Decoration/Model/StringConstraints.elm

Create the Decoration Model

---

cli/src/Morphir/Web/DevelopApp.elm
src/Morphir/TestCoverage/Backend.elm

UI test coverage

---

README.md
gulpfile.js
src/Morphir/IR/SDK/Maybe.elm
src/Morphir/SDK/Maybe.elm
src/Morphir/SDK/String.elm

Version release 0.18.2

---

README.md

fixed morphir-elm broken links

---

README.md
src/Morphir/IR/SDK/Maybe.elm
src/Morphir/SDK/Maybe.elm
src/Morphir/SDK/String.elm

Has value and equal ignore case

---

lib/main.ts

Remove test code from TS library

---

package-lock.json
package.json

Fix ncc breakages
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF …

Fix release

---

src/Morphir/IR/SDK/Decimal.elm

Fixing Decimal.divWithDefault

---

cli2/src/Morphir/Elm/CLI.elm

Fix missing default deps when running scala-gen

---

src/Morphir/Visual/ViewValue.elm

don't show conversion functiosn for decimal and localdate

---

package-lock.json
package.json

Update express to 4.19.2 to address CVE-2024-29041

---

src/Morphir/Generator/API.elm
src/Morphir/Generator/ValueGenerators.elm

Fix errors in Elm around Generator

---

.github/workflows/nodejs.yml
package.json

Deployment fix

---

elm.json
package-lock.json
src/Morphir/IR/SDK/Json/Decode.elm
src/Morphir/IR/SDK/Json/Encode.elm
src/Morphir/SDK/Json/Decode.elm
src/Morphir/SDK/Json/Encode.elm
src/Morphir/SDK/LocalDate.elm
tests/Morphir/SDK/Json/DecodeTests.elm
tests/Morphir/SDK/Json/EncodeTests.elm

Adding encoders and decoders for json

---

.github/workflows/nodejs.yml

Sonatype SCA scan will now occur after build only if the owner is 'finos'. 
> …

feat: Added Sonatype SCA Scan to project

---

cli/morphir-elm-treeview.js
cli/morphir-elm.js
cli/package-lock.json
cli/package.json
cli/treeview/src/index.ts
cli/treeview/src/treeNode.ts
cli/treeview/tsconfig.json
cli/treeview/webpack.config.js

Initial Collapsible Treeview Implementation
- Set up cli and local webpage.
- Typescript & webpack config.
- Initial pass at logic based on the 'Rentals' example.
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, …

Initial Collapsible Treeview Implementation

---

.github/workflows/nodejs.yml

This PR updates the GitHub Actions workflow to use the `pull_request_target` event trigger instead of `pull_request`.
The pull_request_target trigger runs workflows in the context of the target branch, enabling access to secrets and environment variables for pull requests originating from forks. This is essential for workflows like Sonatype Lifecycle scans, which require access to these secrets.
Key Considerations:
- Security Risk: Using pull_request_target allows PRs from forks to access sensitive data, but only after maintainers explicitly approve the workflow.
- Mitigation: Maintainers must review PRs carefully before approving workflows, especially when workflow files are modified, to prevent unauthorized access to secrets.
Please review and let me know if further adjustments are …

Update Action Trigger

---

morphir-ts/src/exports/sdk.ts
morphir-ts/src/sdk/maybe.ts
tests-integration/typescript/morphir/sdk/maybe.test.ts

Add `Maybe` type to TS SDK

---

.github/workflows/nodejs.yml

Temporarily turn-off SCA scanning until issues are resolved

---

README.md

Updated readme.md to call -f for the old cli for the time being

---

morphir-ts/src/exports/sdk.ts
morphir-ts/src/sdk/basics.ts
morphir-ts/src/sdk/maybe.ts
package-lock.json
package.json
tests-integration/typescript/morphir/sdk/basics.test.ts
tests-integration/typescript/morphir/sdk/maybe.test.ts

Add equal method to TypeScript SDK Maybe type

---

elm.json
morphir.json
src/Morphir/IR/Source.elm

Expose Morphir.IR.Source

---

.github/workflows/sonatype-lifecycle.yml

Fix issues with the SCA scan

---

.github/workflows/nodejs.yml
.github/workflows/sonatype-lifecycle.yml

Fix sca scan

---

cli/elm.json
cli/src/Morphir/Web/DevelopApp.elm
src/Morphir/Visual/Components/DatePickerComponent.elm
src/Morphir/Visual/Components/DecisionTable.elm
src/Morphir/Visual/Components/Picklist.elm
src/Morphir/Visual/ValueEditor.elm
src/Morphir/Visual/ViewValue.elm

- Simplified the view function in DatePickerComponent by removing unnecessary HTML elements and directly using Element.html for the input.
- Updated the viewCustomTypeEditor function signature in ValueEditor to remove the unused labelStyle parameter.
- Renamed definitionBody to viewDefinitionBody in ViewValue for clarity and updated references accordingly.
- Adjusted various attributes and styles in Picklist and DecisionTable components for improved layout and consistency.
- Enhanced the handling of optional fields in the RecordEditor section of ValueEditor for better state management.
>
> THIS SOFTWARE IS LICENSED BY …

Refactor DatePickerComponent and ViewValue module

---

.github/workflows/npm-release.yml

Automate npm release
