finos/morphir-elm

- cli/morphir.js
- cli/src/Morphir/Elm/EncodersCLI.elm
- package.json
- src/Morphir/Elm/Backend/Codec/Gen.elm
- src/Morphir/Elm/Frontend.elm
- src/Morphir/IR/AccessControlled.elm
- src/Morphir/IR/Advanced/Type.elm
- src/Morphir/IR/FQName.elm
- tests/Morphir/Codec/Examples.elm
- tests/Morphir/Codec/Tests/A.elm
> First draft of elm encoder backend

- src/Morphir/IR/SDK/Date.elm
- src/Morphir/SDK/Date.elm
- src/Morphir/SDK/LocalDate.elm
- tests/Morphir/SDK/LocalDateTests.elm
> LocalDate intro

- cli/src/Morphir/Elm/CLI.elm
- src/Morphir/IR/Package.elm
- tests-integration/reference-model/morphir.json
- tests-integration/reference-model/src/Morphir/Reference/Model/Issues/Common.elm
- tests-integration/reference-model/src/Morphir/Reference/Model/Issues/Issue227.elm
> Type inference bug fix

- src/Morphir/Scala/Backend.elm
- tests-integration/reference-model/morphir.json
- tests-integration/reference-model/src/Morphir/Reference/Model/Issues/Issue330.elm
- tests-integration/reference-model/src/Morphir/Reference/Model/Issues/Issue331.elm
closes #330, #331 
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF …
> Scala gen fixes

- cli/cli.js
- cli/morphir-elm-gen.js
- gulpfile.js
- package-lock.json
- package.json
closes #10 
closes #383 
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF …
> Add option to copy the SDK with the generated files

- src/Morphir/Visual/DecisionTable.elm
- src/Morphir/Visual/ViewPatternMatch.elm
Headers and table content will use viewValue function instead of manually determining how to visualize values on a case-by-case basis. Table has improved styling for headers and nested elements. decomposeInput function will only provide a different return value to the input if the subject requires unpacking (tuple/record/etc.)
> Pattern match visualization updates 

- gulpfile.js
- package-lock.json
- package.json
Following https://github.com/finos/morphir/discussions/58, I moved the test tasks to `gulpfile.js`. Using [execa](https://www.npmjs.com/package/execa) makes it not too painful to run arbitrary commands.
Then I added new integration tests for TypeScript backend. Currently the 'gen' stage passes but the 'build' stage fails due to issues we're tackling separately.
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF …
> Migrate tests to Gulpfile and add TypeScript integration tests

- src/Morphir/IR/SDK.elm
- src/Morphir/IR/SDK/Dict.elm
- src/Morphir/Value/Error.elm
> Implemented some native functions for the dict module. #523

- src/Morphir/Elm/Frontend.elm
- src/Morphir/Elm/Frontend/Codec.elm
- src/Morphir/Type/Infer/Codec.elm
- src/Morphir/Type/MetaType/Codec.elm
- tests/Morphir/Elm/FrontendTests.elm
Added a new function to the Elm frontend that allows parsing a single expression. This also required eliminating the limitation on having to specify type signatures. #564
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT …
> Support parsing a single Elm expression, eliminate the need for type signatures

- docs/developers-guide/files/spark-backend.md
- src/Morphir/Spark/AST.elm
- tests-integration/spark/model/src/SparkTests/TypeTests.elm
- tests-integration/spark/test/src/SparkTypeTest.scala
I have some (untested) translation of comparisons against Nothing into checking whether a column is null.
My pattern match in Spark/AST.elm looks extremely clumsy so I'd appreciate some advice on how to make it more readable.
There are tests, but they currently don't work because I'm having trouble generating a valid dataframe that has a column that may be a boolean or null.
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF …
> Translate Maybes in Spark

- docs/developers-guide/files/spark-backend.md
> Add documentation for Spark Enum types

- tests-integration/spark/model/src/SparkTests/AntiqueRulesTests.elm
I'm not sure why the CI passed and my local build failed, but the codebase seemed to be missing a file.
This PR creates it where it seems to be required.
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT …
> Add missing file for running 'gulp testIntegration'

- .github/workflows/nodejs.yml
Reverts finos/morphir-elm#822
It didn't work
<details>
<summary>📦 Published PR as canary version: <code>2.65.5--canary.824.2735562135.0</code></summary>
<br />
:sparkles: Test out this PR locally via:
```bash
npm install morphir-elm@2.65.5--canary.824.2735562135.0
yarn add morphir-elm@2.65.5--canary.824.2735562135.0
```
</details>
> Revert "Trying to fix the npm deploy"

- docs/developers-guide/files/spark-testing-framework.md
- gulpfile.js
- tests-integration/spark/elm-tests/src/AntiqueAgeDataSource.elm
- tests-integration/spark/elm-tests/src/AntiqueNameDataSource.elm
- tests-integration/spark/elm-tests/src/AntiqueProductDataSource.elm
- tests-integration/spark/elm-tests/src/AntiqueSSDataSource.elm
- tests-integration/spark/elm-tests/src/FooBoolDataSource.elm
- tests-integration/spark/elm-tests/src/FooFloatDataSource.elm
- tests-integration/spark/elm-tests/src/FooIntDataSource.elm
- tests-integration/spark/elm-tests/src/FooMaybeBoolDataSource.elm
- tests-integration/spark/elm-tests/src/FooMaybeFloatDataSource.elm
- tests-integration/spark/elm-tests/src/FooMaybeIntDataSource.elm
- tests-integration/spark/elm-tests/src/FooMaybeStringDataSource.elm
- tests-integration/spark/elm-tests/src/FooStringDataSource.elm
- tests-integration/spark/elm-tests/tests/GenerateAntiqueAgeData.elm
- tests-integration/spark/elm-tests/tests/GenerateAntiqueNameData.elm
- tests-integration/spark/elm-tests/tests/GenerateAntiqueProductData.elm
- tests-integration/spark/elm-tests/tests/GenerateAntiqueSSData.elm
- tests-integration/spark/elm-tests/tests/GenerateAntiquesData.elm
- tests-integration/spark/elm-tests/tests/GenerateFooBoolData.elm
- tests-integration/spark/elm-tests/tests/GenerateFooFloatData.elm
- tests-integration/spark/elm-tests/tests/GenerateFooIntData.elm
- tests-integration/spark/elm-tests/tests/GenerateFooMaybeBoolData.elm
- tests-integration/spark/elm-tests/tests/GenerateFooMaybeFloatData.elm
- tests-integration/spark/elm-tests/tests/GenerateFooMaybeIntData.elm
- tests-integration/spark/elm-tests/tests/GenerateFooMaybeStringData.elm
- tests-integration/spark/elm-tests/tests/GenerateFooStringData.elm
- tests-integration/spark/elm-tests/tests/create_csv_files.sh
- tests-integration/spark/test/src/spark_test_data/expected_results_christmas_bonanza_15percent_priceRange.csv
Replaced the need for manual tests generators in the create_csv_files.sh file with loops that iterate over Test*.elm and Generate*.elm files in the "tests-integration/spark/elm-tests/tests" directory, execute the test data and create output files.
Updated the documentation for spark tests.
Addressed issue #866
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT …
> Automate execution for Spark CSV generators

- src/Morphir/IR/Module.elm
- src/Morphir/IR/Type.elm
- tests-integration/reference-model/src/Morphir/Reference/Model/Issues/Issue962.elm
> Make sure type inference finds local private constructors

- src/Morphir/Scala/AST.elm
- src/Morphir/Scala/Feature/Core.elm
- src/Morphir/Scala/PrettyPrinter.elm
> Added fix for custom types which has constructor with no arguments

- src/Morphir/Scala/Feature/Core.elm
- tests-integration/reference-model/src/Morphir/Reference/Model/TypeAscription.elm
> LetRecursion function argument curry in Scala Backend

- cli2/morphir-scala-gen.ts
> Fixed include-codecs option for morphir scala-gen

- src/Morphir/Elm/IncrementalFrontend/Mapper.elm
> elm frontend negative literal impl switched from apply to reference

- src/Morphir/SDK/LocalDate.elm
- tests/Morphir/SDK/LocalDateTests.elm
Additional functions for LocalDate needed for business rules and morphir-scala
In particular there is a need to provide infallible constructors for `LocalDate`, so the following were added:
- `fromRataDie`
- `fromCalendarDate`
- `fromOrdinalDate`
> NOTE: `fromCalendarDate` uses an internal function `monthToMonth` that function is intentionally left internal.
In order to support converting to and from a Rata Die based date we included some conversions as well:
- `toRataDie`
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, …
> Additional functions for LocalDate needed for business rules and morphir-scala

- .github/workflows/nodejs.yml
- .gitignore
- .nvmrc
- cli2/.gitignore
- gulpfile.js
- package-lock.json
…affects npm pack
NPM uses the `npm-packlist` package to create the package to create or publish a npm package. As of version `6.0.0` of `npm-packlist` root level ignore patterns in `.gitignore` are ignored when you use `files` in `package.json` (however nested are not ignored). 
Issues were arising when publishing because `cli2/.gitignore` contained the `lib` folder which is actually needed in the deploy. Because we want to ignore `cli2/lib` from git because it is generated, but we **DO** want to include the folder in the package, we need to add `cli2/lib/` to the root `.gitignore` file.
Also since it is not clear what version of Node folks are using, I've also added an `.nvmrc` file which is currently set to `lts/hydrogen` (version 18.x) which is  an LTS version in Maintenance mode …
> Fix release

- cli/src/Morphir/Web/DevelopApp.elm
- src/Morphir/Visual/Components/SectionComponent.elm
- src/Morphir/Visual/Components/TabsComponent.elm
> Use lazy loading for content in tabs and sections

- cli2/cli.ts
- cli2/dependencies.ts
- cli2/morphir-make.ts
- package-lock.json
- package.json
Improve how the Morphir CLI handles dependencies and add "includes" to allow providing dependencies at the command line
The Morphir CLI has had support for some time for models to depend on other models using `localDependencies` in their `morphir.json` file. While this feature is not particularly well documented, users who have taken advantage of this feature have hit on some difficulties. The primary issue is that the dependencies must be a local IR file, as each local dependency expected to be an existing Morphir IR on local disk (this means a JSON serialized Morphir IR File).
Users have expressed desires to be able to load dependencies from remote locations. Also, it would be nice if it were easier to share dependencies.
Ways we want to enable to load dependencies:
NOTE: That to start …
> Improve how the Morphir CLI handles dependencies and add "includes" to allow providing dependencies at the command line

- cli2/morphir.ts
- package-lock.json
- package.json
> Disable the test-data-generation portion of the CLI since the feature is broken

- .gitignore
- cli2/cli.ts
- cli2/dependencies.test.ts
- cli2/dependencies.ts
- cli2/get-uri-wrapper.test.ts
- cli2/get-uri-wrapper.ts
- gulpfile.js
- package-lock.json
- package.json
- tests-integration/cli2-qa-test/cli2.dependencies.test.ts
- tests-integration/cli2-qa-test/test-data/README.md
- tests-integration/cli2-qa-test/test-data/business-terms/README.md
- tests-integration/cli2-qa-test/test-data/business-terms/elm.json
- tests-integration/cli2-qa-test/test-data/business-terms/morphir.json
- tests-integration/cli2-qa-test/test-data/business-terms/src/Morphir/Remote/App/BusinessTerms.elm
- tests-integration/cli2-qa-test/test-data/rentals-decomposed/elm.json
- tests-integration/cli2-qa-test/test-data/rentals-decomposed/src/Morphir/Partial/App/Analytics.elm
- tests-integration/cli2-qa-test/test-data/rentals-decomposed/src/Morphir/Partial/App/Forecast.elm
- tests-integration/cli2-qa-test/test-data/rentals-decomposed/src/Morphir/Partial/App/Rentals.elm
- tests-integration/cli2-qa-test/test-data/rentals-decomposed/src/Morphir/Partial/App/Winds.elm
- tests/Morphir/Elm/FrontendTests.elm
This PR contains the following: 
- Fixing the support for Http and File dependencies on the `dependencies` property of morphir.json file
- Fixing the `localDependencies` compatibility
- Integration tests for local and dependencies 
- Unit tests for the dependencies module
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY …
> Dependency fix on typescript CLI

- .github/workflows/nodejs.yml
- package-lock.json
- package.json
- src/Morphir/Elm/Frontend.elm
- src/Morphir/Elm/Frontend/Codec.elm
- tests-integration/cli/cli.test.ts
- tests-integration/cli2-qa-test/cli2QA.test.ts
> Report invalid exposed modules

- src/Morphir/IR/SDK.elm
- src/Morphir/IR/SDK/Instant.elm
- src/Morphir/SDK/Instant.elm
> Added Instant module (originally implemented by Stephen Torku)
